const types = {
  AUTHORIZED: "AUTHORIZED",
  HANDLE_USER_DATA: "HANDLE_USER_DATA",
  HANDLE_TEXT: "HANDLE_TEXT",
  USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",
  USER_UPDATE_FAIL: "USER_UPDATE_FAIL",
  CLEAR_GEN_STATE: "CLEAR_GEN_STATE",
  HANDLE_CONTENT_MANAGER_TEXT: "HANDLE_CONTENT_MANAGER_TEXT",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAIL: "LOGIN_USER_FAIL",
  CONTENT_POST_SUCCESS: "CONTENT_POST_SUCCESS",
  CONTENT_POST_FAIL: "CONTENT_POST_FAIL",
  GOT_GUIDE_DATA:"GOT_GUIDE_DATA",
  GOT_BLOG_DATA:"GOT_BLOG_DATA"
};
export default types;
