const types = {
  AUTHORIZED: "AUTHORIZED",
  SET_LOGIN_TEXT: "SET_LOGIN_TEXT",
  HANDLE_CONTENT_MANAGER_TEXT:'HANDLE_CONTENT_MANAGER_TEXT',
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAIL:"LOGIN_USER_FAIL",
  IS_AUTHED:"IS_AUTHED"
};
export default types;
